//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkedCheckersServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Highscore
    {
        public int Id { get; set; }
        public string DateTime { get; set; }
        public short MoveCount { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
